### ISSUE TITLE
[Bug] No module installation possible

### ISSUE THREAD

**Issue by SirMotte** [prolice/auto-color-folder#1]
Just wanted to let you know, that the installation of this module is currently not possible. In addition several error messages are shown, that warn about outdated dependencies. Here's the console warning:
![grafik](https://user-images.githubusercontent.com/82598692/194733300-ec59eec9-4689-47b3-9cc6-efcf56061d8b.png)

Tested with Version 10 - Build 287, Stable

**Comment by prolice** [comment]
Module not ready for VTT 10 actualy, it is mentioned in the compatibility version part of the module on the web site FoundryVTT.com

**Comment by prolice** [comment]
A 1.0.0 version has been released compatible with Foundry 10
