### ISSUE TITLE
Foundry v11

### ISSUE THREAD

**Issue by JohanFalt** [prolice/auto-color-folder#3]
No real comment. If possible it would make my group happy.

**Comment by prolice** [comment]
What is the issue ?

**Comment by JohanFalt** [comment]
You have set the max version of Foundry to 10 so it can’t be run on 11.

**Comment by prolice** [comment]
Ok, I plan to test the module in FVTT 11 next week.
It will release at least on friday 16th

BR ;-)

**Comment by prolice** [comment]
It was quick in fact nothing to do but test...
So it is already released on v1.1.0
