### ISSUE TITLE
[Feature Request] Extend Functionality to Compendia

### ISSUE THREAD

**Issue by harrisog** [prolice/auto-color-folder#5]
Apologies, I should have been clearer with my previous request. While it is great and useful to have colors in the compendium tab now, what I meant by "compendium browser" (a confusing choice of words) were really the compendia themselves (picture attached). It would probably be best and easiest to just to extend the same color pattern to each compendium type as the tabs.
![compendiumfoldercolors](https://github.com/prolice/auto-color-folder/assets/13065830/ff400f25-a36e-48b7-9029-e15841b9be63)

**Comment by prolice** [comment]
Hello this is another level.
It would be nice yes, but I have to estimate the charge for this change.
The rendering point is not the same, the color management is not the same.
Keep in my mind for the futur

**Comment by prolice** [comment]
Finally, I found a solution but you have to define the same color on your Compendium directories as your Compendium(a) browser.
![image](https://github.com/prolice/auto-color-folder/assets/48445910/5fb1bb1f-be08-49c8-85ae-c1990f50fb8a)
version 1.3.0
